# Generated by Django 3.1.6 on 2021-03-27 07:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ordeplaced',
            new_name='Orderplaced',
        ),
    ]
