# Generated by Django 3.1.6 on 2021-04-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20210408_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikes',
            name='age_category',
            field=models.CharField(default=12, max_length=15),
        ),
        migrations.AlterField(
            model_name='bikes',
            name='bike_categories',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bikes',
            name='color',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='bikes',
            name='description',
            field=models.TextField(default='Bicycle'),
        ),
        migrations.AlterField(
            model_name='bikes',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='bikes',
            name='name',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='bikes',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bikes',
            name='size',
            field=models.CharField(max_length=2),
        ),
    ]
